// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mini.CleanArc.Infrastructure.Persistence;

#nullable disable

namespace Mini.CleanArc.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251216125956_CreatedDb")]
    partial class CreatedDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Mini.CleanArc.Core.Domain.Entity.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignedUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DueDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedUserId = 2,
                            Description = "Haftalık ekip toplantısı için sunum hazırla",
                            DueDate = "2025-12-20",
                            Status = "Pending",
                            Title = "Toplantı hazırlığı"
                        },
                        new
                        {
                            Id = 2,
                            AssignedUserId = 5,
                            Description = "Finans raporunu yöneticilere gönder",
                            DueDate = "2025-12-18",
                            Status = "InProgress",
                            Title = "Rapor gönderimi"
                        },
                        new
                        {
                            Id = 3,
                            AssignedUserId = 4,
                            Description = "Yeni arayüzü test et ve geri bildirim yaz",
                            DueDate = "2025-12-15",
                            Status = "Completed",
                            Title = "Kullanıcı testi"
                        },
                        new
                        {
                            Id = 4,
                            AssignedUserId = 1,
                            Description = "Günlük yedekleme işlemini kontrol et",
                            DueDate = "2025-12-17",
                            Status = "Pending",
                            Title = "Veritabanı yedeği"
                        },
                        new
                        {
                            Id = 5,
                            AssignedUserId = 3,
                            Description = "Yeni ürün tanıtımı için e-posta içeriği oluştur",
                            DueDate = "2025-12-22",
                            Status = "InProgress",
                            Title = "E-posta kampanyası"
                        });
                });

            modelBuilder.Entity("Mini.CleanArc.Core.Domain.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmet.yilmaz@example.com",
                            Name = "Ahmet Yılmaz",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "ayse.demir@example.com",
                            Name = "Ayşe Demir",
                            Role = "User"
                        },
                        new
                        {
                            Id = 3,
                            Email = "mehmet.kaya@example.com",
                            Name = "Mehmet Kaya",
                            Role = "User"
                        },
                        new
                        {
                            Id = 4,
                            Email = "elif.sahin@example.com",
                            Name = "Elif Şahin",
                            Role = "User"
                        },
                        new
                        {
                            Id = 5,
                            Email = "can.oz@example.com",
                            Name = "Can Öz",
                            Role = "Manager"
                        });
                });

            modelBuilder.Entity("Mini.CleanArc.Core.Domain.Entity.TaskItem", b =>
                {
                    b.HasOne("Mini.CleanArc.Core.Domain.Entity.User", "AssignedUser")
                        .WithMany("Tasks")
                        .HasForeignKey("AssignedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedUser");
                });

            modelBuilder.Entity("Mini.CleanArc.Core.Domain.Entity.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
